title: "Affiliates"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
# permalink: "/:title/"
permalink: :name
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: yt
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1
remote_theme: wowthemesnet/affiliates-jekyll-theme

# Authors
authors:
  yt:
    name: Yummy and Tummy
    display_name: Yummy and Tummy
    avatar: 'assets/images/sal.png'
    email: admin@yummytummy.ph
    web: https://www.yummytummy.ph
    twitter: https://twitter.com/yummytummyph
    description: "We are Yummy and Tummy"
  alaine:
    name: Alaine
    display_name: Chef A
    avatar: 'assets/images/john.png'
    email: chef@yummytummy.ph
    web: https://instagram.com/chefalaine
    twitter: https://twitter.com/chefalaine
    description: "Hi! I'm Chef Alaine."
  rye:
    name: Ryan
    display_name: Coach Rye
    avatar: 'assets/images/john.png'
    email: rye@coachrye.com
    web: https://instagram.com/coachrye
    twitter: https://twitter.com/coachrye34
    description: "Hi! I'm Coach Rye."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
